FD limit at: 65535
zookeeper error on zoo_create, path /rtb-test/serviceClass/rtbRequestRouter/router: node exists

--------------------------[Exception thrown]---------------------------
time:   2015-06-05T16:43:31Z
type:   ML::Exception
pid:    10229; tid: 10229
what:   Zookeeper error on zoo_create, path /rtb-test/serviceClass/rtbRequestRouter/router: node exists
stack:
00: 0x0x7f5b11577ecb at __cxa_throw + 0xbb in /home/ubuntu/rtbkit/build/x86_64/bin/../bin/libexception_hook.so + 0xecb/home/ubuntu/rtbkit/build/x86_64/bin/../bin/libexception_hook.so(__cxa_throw+0xbb) [0x7f5b11577ecb]
01: 0x0x7f5b0f1b8e63 at Datacratic::ZookeeperConnection::checkRes(int, int&, char const*, char const*) + 0xe3 in /home/ubuntu/rtbkit/build/x86_64/bin/../bin/libservices.so + 0x139e63/home/ubuntu/rtbkit/build/x86_64/bin/../bin/libservices.so(_ZN10Datacratic19ZookeeperConnection8checkResEiRiPKcS3_+0xe3) [0x7f5b0f1b8e63]
02: 0x0x7f5b0f1b8a61 at Datacratic::ZookeeperConnection::createNode(std::string const&, std::string const&, bool, bool, bool, bool) + 0x441 in /home/ubuntu/rtbkit/build/x86_64/bin/../bin/libservices.so + 0x139a61/home/ubuntu/rtbkit/build/x86_64/bin/../bin/libservices.so(_ZN10Datacratic19ZookeeperConnection10createNodeERKSsS2_bbbb+0x441) [0x7f5b0f1b8a61]
03: 0x0x7f5b0f165a85 at Datacratic::ZookeeperConfigurationService::setUnique(std::string const&, Json::Value const&) + 0x285 in /home/ubuntu/rtbkit/build/x86_64/bin/../bin/libservices.so + 0xe6a85/home/ubuntu/rtbkit/build/x86_64/bin/../bin/libservices.so(_ZN10Datacratic29ZookeeperConfigurationService9setUniqueERKSsRKN4Json5ValueE+0x285) [0x7f5b0f165a85]
04: 0x0x7f5b0f1504d4 at Datacratic::ServiceBase::registerServiceProvider(std::string const&, std::vector<std::string, std::allocator<std::string> > const&) + 0x1c4 in /home/ubuntu/rtbkit/build/x86_64/bin/../bin/libservices.so + 0xd14d4/home/ubuntu/rtbkit/build/x86_64/bin/../bin/libservices.so(_ZN10Datacratic11ServiceBase23registerServiceProviderERKSsRKSt6vectorISsSaISsEE+0x1c4) [0x7f5b0f1504d4]
05: 0x0x7f5b10e834b4 at RTBKIT::Router::init() + 0xd4 in /home/ubuntu/rtbkit/build/x86_64/bin/../bin/librtb_router.so + 0x814b4/home/ubuntu/rtbkit/build/x86_64/bin/../bin/librtb_router.so(_ZN6RTBKIT6Router4initEv+0xd4) [0x7f5b10e834b4]
06: 0x0x42c009 at RTBKIT::RouterRunner::init() + 0x529 in build/x86_64/bin/router_runner + 0x2c009build/x86_64/bin/router_runner(_ZN6RTBKIT12RouterRunner4initEv+0x529) [0x42c009]
07: 0x0x4276ca at main + 0x7a in build/x86_64/bin/router_runner + 0x276cabuild/x86_64/bin/router_runner(main+0x7a) [0x4276ca]
08: 0x0x7f5b0ffe276d at __libc_start_main + 0xed in /lib/x86_64-linux-gnu/libc.so.6 + 0x2176d/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xed) [0x7f5b0ffe276d]
09: 0x0x427fbd in build/x86_64/bin/router_runner + 0x27fbdbuild/x86_64/bin/router_runner() [0x427fbd]

terminate called after throwing an instance of 'ML::Exception'
  what():  Zookeeper error on zoo_create, path /rtb-test/serviceClass/rtbRequestRouter/router: node exists
